/**
 * life-path.ts
 *
 * Type definitions for the Life Path System.
 *
 * Deliberately kept separate from the core Mind365 types (index.ts)
 * so this module can evolve independently and be tree-shaken if unused.
 */

// ── Goal ──────────────────────────────────────────────────────────────────────

/** A single quantifiable life goal the user is working toward. */
export interface UserGoal {
  id: string;

  /** Human-readable name, e.g. "Save $1,000,000" */
  title: string;

  /** The numeric milestone to reach, e.g. 1_000_000 */
  targetValue: number;

  /** How far the user has already progressed, e.g. 230_000 */
  currentValue: number;

  /**
   * Optional deadline as an ISO date string (yyyy-MM-dd).
   * Omit when the goal has no time constraint.
   */
  deadline?: string;
}

// ── Life Direction ─────────────────────────────────────────────────────────────

/**
 * A life direction (theme/pillar) that groups related behaviors.
 * Examples: "Wealth", "Health", "Relationships", "Learning".
 */
export interface LifeDirection {
  id: string;

  /** Display name of this direction, e.g. "Wealth" */
  name: string;

  /**
   * Keywords representing actions that move the user *toward* this direction.
   * Matched case-insensitively against daily log content.
   * e.g. ["study", "read", "exercise"]
   */
  positiveActions: string[];

  /**
   * Keywords representing actions that move the user *away from* this direction.
   * e.g. ["scrolling", "procrastinate", "binge"]
   */
  negativeActions: string[];
}

// ── Daily Log (Life Path variant) ─────────────────────────────────────────────

/**
 * A daily reflection entry enriched with extracted behavioral signals.
 * This is the Life Path variant; it is distinct from the core DailyLog
 * in index.ts to keep concerns separated.
 */
export interface LifePathLog {
  id: string;

  /** ISO date string (yyyy-MM-dd) of when this log was written */
  date: string;

  /** Free-form journal content written by the user */
  content: string;

  /**
   * Action keywords extracted from `content`.
   * Populated by `detectActions()` or by external NLP / AI analysis.
   */
  detectedActions: string[];
}

// ── Result shapes ─────────────────────────────────────────────────────────────

/** Per-direction scoring breakdown inside an AlignmentResult. */
export interface DirectionBreakdown {
  directionId: string;
  directionName: string;

  /** Positive keywords found in this direction */
  positiveHits: string[];

  /** Negative keywords found in this direction */
  negativeHits: string[];

  /** Net point delta for this direction (positive − negative) */
  delta: number;
}

/** The full result returned by `calculateAlignmentScore()`. */
export interface AlignmentResult {
  /**
   * Final alignment score clamped to [0, 100].
   * 50 = perfectly neutral; >50 = net positive day; <50 = net negative day.
   */
  score: number;

  /** All positive action keywords that were matched */
  positiveMatches: string[];

  /** All negative action keywords that were matched */
  negativeMatches: string[];

  /** Per-direction breakdown, useful for building detailed UI */
  breakdown: DirectionBreakdown[];
}

// ── AI Mentor ─────────────────────────────────────────────────────────────────

/** A single phase in a goal's breakdown plan. */
export interface GoalPhase {
  index: number;
  title: string;
  /** Brief description of what this phase focuses on */
  description: string;
  /** Human-readable progress range, e.g. "0%–30%" */
  progressRange: string;
  /** 2–4 concrete key actions for this phase */
  keyActions: string[];
  /** True for the phase the user is currently in */
  isCurrent: boolean;
}

/** Weekly action plan generated by the AI mentor. */
export interface WeeklyPlan {
  /** The week's single most important focus theme */
  focus: string;
  /** 3–5 concrete actions to take this week */
  actions: string[];
  /** A short reminder or watchout for the week */
  reminder: string;
}

/** Today's AI-generated suggestion for a goal. */
export interface DailySuggestion {
  /** The one concrete action to take today */
  action: string;
  /** Why this is the most important thing today */
  reason: string;
  /** Optional micro-tip or motivational note */
  tip?: string;
}

/** AI adjustment note returned by the "AI调整建议" action. */
export interface AdjustNote {
  /** Brief assessment of the user's current state */
  assessment: string;
  /** The recommended adjustment */
  adjustment: string;
  /** A short encouraging note */
  encouragement: string;
}

/**
 * The full mentor state for a single UserGoal.
 * Persisted to localStorage keyed by goalId.
 */
export interface MentorPlan {
  goalId: string;

  /** Phase breakdown — generated once, rebuilt on "重新规划" */
  phases: GoalPhase[];

  /** ISO datetime when phases were last generated */
  phasesGeneratedAt: string | null;

  /** Current week plan — regenerated at most once per calendar week */
  weeklyPlan: WeeklyPlan | null;

  /**
   * ISO week key when weeklyPlan was generated, e.g. "2024-W16".
   * Used to decide whether to offer regeneration.
   */
  weeklyGeneratedAt: string | null;

  /** Today's suggestion — regenerated at most once per calendar day */
  dailySuggestion: DailySuggestion | null;

  /** yyyy-MM-dd when dailySuggestion was generated */
  dailyGeneratedAt: string | null;

  /** Latest AI adjustment note */
  adjustNote: AdjustNote | null;
}

// ── Three-layer detection (Rule + AI + Fusion) ────────────────────────────────

/**
 * Whether an action moves the user toward (positive) or away from
 * (negative) their declared life directions.
 */
export type ActionCategory = "positive" | "negative";

/** Where a detected action came from in the three-layer pipeline. */
export type ActionSource = "rule" | "ai";

/**
 * An action extracted by the deterministic rule layer.
 *
 * Rules are pattern-based (regex) and produce high-confidence,
 * machine-verifiable signals such as "学习2小时" → study/2h.
 */
export interface RuleAction {
  /** Canonical action key, e.g. "study", "scrolling" */
  type: string;

  /** Optional parsed duration in hours when the pattern captured one */
  duration?: number;

  /** Whether the rule classifies this as a positive or negative behavior */
  category: ActionCategory;

  source: "rule";

  /** The raw substring that matched, useful for debugging / UI highlights */
  rawMatch?: string;
}

/**
 * An action extracted by the AI / NLP layer.
 *
 * AI results are softer signals — the model returns a confidence value
 * in [0.5, 0.9] that the fusion layer uses as its weight.
 */
export interface AiAction {
  type: string;

  /** Whether the AI classifies this as positive or negative */
  category: ActionCategory;

  /** Model confidence, expected range [0.5, 0.9] */
  confidence: number;

  /** Optional human-readable explanation produced by the model */
  reason?: string;

  source: "ai";
}

/**
 * Output of the fusion layer.
 *
 * `weight` collapses the source semantics into a single multiplier:
 *   - rule actions     → 1.0
 *   - ai   actions     → confidence (0.5–0.9)
 *
 * The scoring layer multiplies POSITIVE_WEIGHT / NEGATIVE_WEIGHT by
 * this `weight` to compute the action's contribution to the day's score.
 */
export interface FusedAction {
  type: string;
  category: ActionCategory;
  source: ActionSource;
  weight: number;

  /** Carried over from the rule layer when present */
  duration?: number;

  /** Carried over from the AI layer when present */
  confidence?: number;
  reason?: string;
}

/** The result returned by `calculateGoalProgress()`. */
export interface GoalProgress {
  /** Progress as a fraction in [0, 1] */
  fraction: number;

  /** Progress as a whole percentage in [0, 100] */
  percentage: number;

  /** How much more is needed to reach the target */
  remaining: number;

  /** True once currentValue >= targetValue */
  isCompleted: boolean;

  /**
   * Calendar days until the deadline (can be negative if overdue).
   * null when no deadline was set.
   */
  daysLeft: number | null;
}
